### ISSUE TITLE
Latest update breaks JSON parser

### ISSUE THREAD

**Issue by rednoah** [jdereg/json-io#111]
Test Case:
```
String s = "{\"accents\":\"verità\"}";
System.out.println(s);
System.out.println(JsonUtilities.readJson(s));
```

Throws:
```
java.lang.IllegalArgumentException
	at java.lang.AbstractStringBuilder.appendCodePoint(AbstractStringBuilder.java:800)
	at java.lang.StringBuilder.appendCodePoint(StringBuilder.java:235)
	at com.cedarsoftware.util.io.JsonParser.readString(JsonParser.java:434)
	at com.cedarsoftware.util.io.JsonParser.readValue(JsonParser.java:246)
	at com.cedarsoftware.util.io.JsonParser.readJsonObject(JsonParser.java:192)
	at com.cedarsoftware.util.io.JsonParser.readValue(JsonParser.java:256)
	at com.cedarsoftware.util.io.JsonReader.readObject(JsonReader.java:634)
	... 4 more
```

EDIT: Works with `4.9.1`. Broken since `4.9.2`.

**Comment by jdereg** [comment]
This was fixed in 4.9.5.  It was introduced in 4.9.2.
