### ISSUE TITLE
4.15 --> 4.16 default mapping method fails to parse

### ISSUE THREAD

**Issue by mlbiam** [jdereg/json-io#234]
When bumping from 4.15 --> 4.16 I began receiving the following errors when trying to encode to json then parse back to java objects:

```
om.cedarsoftware.util.io.JsonIoException: Unable to set field: types on target: null with value: mLen:1 type:[Ljava.lang.String; line:1, col:2370 id:-1
	at com.cedarsoftware.util.io.ObjectResolver.assignField(ObjectResolver.java:290) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.ObjectResolver.traverseFields(ObjectResolver.java:116) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.ObjectResolver.traverseFields(ObjectResolver.java:91) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.Resolver.convertMapsToObjects(Resolver.java:168) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.ObjectResolver.traverseCollection(ObjectResolver.java:505) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.Resolver.convertMapsToObjects(Resolver.java:153) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.ObjectResolver.assignField(ObjectResolver.java:254) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.ObjectResolver.traverseFields(ObjectResolver.java:116) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.ObjectResolver.traverseFields(ObjectResolver.java:91) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.Resolver.convertMapsToObjects(Resolver.java:168) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.ObjectResolver.assignField(ObjectResolver.java:254) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.ObjectResolver.traverseFields(ObjectResolver.java:116) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.ObjectResolver.traverseFields(ObjectResolver.java:91) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.Resolver.convertMapsToObjects(Resolver.java:168) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.ObjectResolver.traverseCollection(ObjectResolver.java:505) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.Resolver.convertMapsToObjects(Resolver.java:153) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.JsonReader.convertParsedMapsToJava(JsonReader.java:1029) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.JsonReader.convertParsedMapsToJava(JsonReader.java:1048) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.JsonReader.readObject(JsonReader.java:959) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.JsonReader.toObjects(JsonReader.java:376) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.JsonReader.toObjects(JsonReader.java:388) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.JsonReader.toObjects(JsonReader.java:403) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.JsonReader.toObjects(JsonReader.java:414) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.JsonReader.jsonToJava(JsonReader.java:427) ~[json-io-4.16.0.jar:?]
	at com.tremolosecurity.provisioning.core.ProvisioningEngineImpl.getWorkflowCopy(ProvisioningEngineImpl.java:1089) ~[classes/:?]
	at com.tremolosecurity.provisioning.core.ProvisioningEngineImpl.getWorkFlow(ProvisioningEngineImpl.java:1037) ~[classes/:?]
	at com.tremolosecurity.provisioning.auth.JITAuthMech.doGet(JITAuthMech.java:126) ~[classes/:?]
	at com.tremolosecurity.provisioning.auth.JITAuthMech.doPost(JITAuthMech.java:75) ~[classes/:?]
	at com.tremolosecurity.proxy.auth.sys.AuthManagerImpl.execAuth(AuthManagerImpl.java:454) ~[classes/:?]
	at com.tremolosecurity.proxy.auth.sys.AuthManagerImpl.nextAuth(AuthManagerImpl.java:134) ~[classes/:?]
	at com.tremolosecurity.proxy.auth.sys.AuthManagerImpl.nextAuth(AuthManagerImpl.java:88) ~[classes/:?]
	at com.tremolosecurity.proxy.auth.FormLoginAuthMech.doPost(FormLoginAuthMech.java:219) ~[classes/:?]
	at com.tremolosecurity.proxy.auth.AuthMgrSys.doAuthMgr(AuthMgrSys.java:198) ~[classes/:?]
	at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:126) ~[classes/:?]
	at com.tremolosecurity.proxy.auth.AzSys.doAz(AzSys.java:89) ~[classes/:?]
	at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:111) ~[classes/:?]
	at com.tremolosecurity.proxy.auth.AuthSys.doAuth(AuthSys.java:88) ~[classes/:?]
	at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:105) ~[classes/:?]
	at com.tremolosecurity.proxy.ConfigSys.doConfig(ConfigSys.java:296) [classes/:?]
	at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:93) [classes/:?]
	at com.tremolosecurity.filter.UnisonServletFilter.doFilter(UnisonServletFilter.java:299) [classes/:?]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:276) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:132) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:256) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:101) [undertow-servlet-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393) [undertow-core-2.3.10.Final.jar:2.3.10.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859) [undertow-core-2.3.10.Final.jar:2.3.10.Final]
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) [jboss-threads-2.3.6.Final.jar:2.3.6.Final]
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982) [jboss-threads-2.3.6.Final.jar:2.3.6.Final]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) [jboss-threads-2.3.6.Final.jar:2.3.6.Final]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377) [jboss-threads-2.3.6.Final.jar:2.3.6.Final]
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282) [xnio-api-3.8.12.Final.jar:3.8.12.Final]
	at java.base/java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalArgumentException: Can not set java.util.ArrayList field com.novell.ldap.util.RDN.types to [Ljava.lang.String;
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
	at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[?:?]
	at java.base/java.lang.reflect.Field.set(Field.java:780) ~[?:?]
	at com.cedarsoftware.util.reflect.injectors.AbstractInjector.tryInject(AbstractInjector.java:74) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.reflect.injectors.AbstractInjector.inject(AbstractInjector.java:65) ~[json-io-4.16.0.jar:?]
	at com.cedarsoftware.util.io.ObjectResolver.assignField(ObjectResolver.java:247) ~[json-io-4.16.0.jar:?]
```

Here's the 4.15 serialized java (works):

```json
{
  "@id": 1,
  "@type": "com.tremolosecurity.provisioning.core.WorkflowImpl",
  "name": "jitdb",
  "tasks": [
    {
      "@type": "com.tremolosecurity.provisioning.tasks.CustomTask",
      "className": "com.tremolosecurity.provisioning.customTasks.LoadGroups",
      "params": {
        "nameAttr": {
          "@type": "com.tremolosecurity.saml.Attribute",
          "values": {
            "@type": "java.util.ArrayList",
            "@items": [
              "uid"
            ]
          },
          "name": "nameAttr",
          "dataType": "string"
        }
      },
      "task": {
        "@type": "com.tremolosecurity.provisioning.customTasks.LoadGroups",
        "nameAttr": "uid",
        "inverse": false,
        "base": null
      },
      "onSuccess": null,
      "onFailure": null,
      "workflow": {
        "@ref": 1
      },
      "isOnHold": false,
      "isDone": false,
      "wasSuccess": false
    },
    {
      "@type": "com.tremolosecurity.provisioning.tasks.CustomTask",
      "className": "com.tremolosecurity.provisioning.customTasks.MapJitGroups",
      "params": {
        "groupMap": {
          "@type": "com.tremolosecurity.saml.Attribute",
          "values": {
            "@type": "java.util.ArrayList",
            "@items": [
              "k8s-cluster-administrators=CN=jit-k8s-admin,CN=Users,DC=ent2k12,DC=domain,DC=com",
              "administrators=CN=ouadmins,CN=Users,DC=ent2k12,DC=domain,DC=com"
            ]
          },
          "name": "groupMap",
          "dataType": "string"
        },
        "attributeName": {
          "@type": "com.tremolosecurity.saml.Attribute",
          "values": {
            "@type": "java.util.ArrayList",
            "@items": [
              "memberOf"
            ]
          },
          "name": "attributeName",
          "dataType": "string"
        }
      },
      "task": {
        "@type": "com.tremolosecurity.provisioning.customTasks.MapJitGroups",
        "groupMap": {
          "@type": "java.util.HashMap",
          "@keys": [
            {
              "@type": "com.novell.ldap.util.DN",
              "rdnList": [
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": [
                    "CN"
                  ],
                  "values": [
                    "jit-k8s-admin"
                  ],
                  "rawValue": "jit-k8s-admin"
                },
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": [
                    "CN"
                  ],
                  "values": [
                    "Users"
                  ],
                  "rawValue": "Users"
                },
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": [
                    "DC"
                  ],
                  "values": [
                    "ent2k12"
                  ],
                  "rawValue": "ent2k12"
                },
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": [
                    "DC"
                  ],
                  "values": [
                    "domain"
                  ],
                  "rawValue": "domain"
                },
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": [
                    "DC"
                  ],
                  "values": [
                    "com"
                  ],
                  "rawValue": "com"
                }
              ]
            },
            {
              "@type": "com.novell.ldap.util.DN",
              "rdnList": [
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": [
                    "CN"
                  ],
                  "values": [
                    "ouadmins"
                  ],
                  "rawValue": "ouadmins"
                },
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": [
                    "CN"
                  ],
                  "values": [
                    "Users"
                  ],
                  "rawValue": "Users"
                },
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": [
                    "DC"
                  ],
                  "values": [
                    "ent2k12"
                  ],
                  "rawValue": "ent2k12"
                },
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": [
                    "DC"
                  ],
                  "values": [
                    "domain"
                  ],
                  "rawValue": "domain"
                },
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": [
                    "DC"
                  ],
                  "values": [
                    "com"
                  ],
                  "rawValue": "com"
                }
              ]
            }
          ],
          "@items": [
            {
              "@type": "java.util.ArrayList",
              "@items": [
                "k8s-cluster-administrators"
              ]
            },
            {
              "@type": "java.util.ArrayList",
              "@items": [
                "administrators"
              ]
            }
          ]
        },
        "attributeName": "memberOf"
      },
      "onSuccess": null,
      "onFailure": null,
      "workflow": {
        "@ref": 1
      },
      "isOnHold": false,
      "isDone": false,
      "wasSuccess": false
    },
    {
      "@type": "com.tremolosecurity.provisioning.tasks.Mapping",
      "mapper": {
        "map": {
          "sub": {
            "@type": "com.tremolosecurity.provisioning.mapping.MappingEntry",
            "type": "userAttr",
            "destType": null,
            "userAttr": "uid",
            "staticValue": null,
            "mapping": null,
            "composite": null
          },
          "firstName": {
            "@type": "com.tremolosecurity.provisioning.mapping.MappingEntry",
            "type": "userAttr",
            "destType": null,
            "userAttr": "givenName",
            "staticValue": null,
            "mapping": null,
            "composite": null
          },
          "lastName": {
            "@type": "com.tremolosecurity.provisioning.mapping.MappingEntry",
            "type": "userAttr",
            "destType": null,
            "userAttr": "sn",
            "staticValue": null,
            "mapping": null,
            "composite": null
          },
          "TREMOLO_USER_ID": {
            "@type": "com.tremolosecurity.provisioning.mapping.MappingEntry",
            "type": "userAttr",
            "destType": null,
            "userAttr": "uid",
            "staticValue": null,
            "mapping": null,
            "composite": null
          },
          "mail": {
            "@type": "com.tremolosecurity.provisioning.mapping.MappingEntry",
            "type": "userAttr",
            "destType": null,
            "userAttr": "mail",
            "staticValue": null,
            "mapping": null,
            "composite": null
          }
        },
        "attributes": [
          "sub",
          "firstName",
          "lastName",
          "TREMOLO_USER_ID",
          "mail"
        ],
        "strict": false
      },
      "strict": true,
      "onSuccess": [
        {
          "@type": "com.tremolosecurity.provisioning.tasks.AddGroup",
          "name": "users",
          "remove": false,
          "onSuccess": null,
          "onFailure": null,
          "workflow": {
            "@ref": 1
          },
          "isOnHold": false,
          "isDone": false,
          "wasSuccess": false
        },
        {
          "@type": "com.tremolosecurity.provisioning.tasks.Provision",
          "isSync": true,
          "setPassword": false,
          "targetName": "jitdb",
          "onlyPassedInAttributes": false,
          "attributes": [
            "sub",
            "firstName",
            "lastName",
            "mail"
          ],
          "onSuccess": null,
          "onFailure": null,
          "workflow": {
            "@ref": 1
          },
          "isOnHold": false,
          "isDone": false,
          "wasSuccess": false
        },
        {
          "@type": "com.tremolosecurity.provisioning.tasks.Resync",
          "keepExternalAttrs": false,
          "changeRoot": true,
          "newRoot": "o=Tremolo",
          "onSuccess": null,
          "onFailure": null,
          "workflow": {
            "@ref": 1
          },
          "isOnHold": false,
          "isDone": false,
          "wasSuccess": false
        }
      ],
      "onFailure": [],
      "workflow": {
        "@ref": 1
      },
      "isOnHold": false,
      "isDone": false,
      "wasSuccess": false
    }
  ],
  "id": 0,
  "user": null,
  "requester": null,
  "request": null,
  "userNum": 0,
  "requesterNum": 0,
  "description": "JIT",
  "label": "JIT",
  "annotationFilters": {
    "@type": "java.util.HashMap"
  }
}
```

and here's the 4.16 generated json (does not work):

```json
{
  "@id": 1,
  "@type": "com.tremolosecurity.provisioning.core.WorkflowImpl",
  "name": "jitdb",
  "tasks": [
    {
      "@type": "com.tremolosecurity.provisioning.tasks.CustomTask",
      "className": "com.tremolosecurity.provisioning.customTasks.LoadGroups",
      "params": {
        "nameAttr": {
          "@type": "com.tremolosecurity.saml.Attribute",
          "values": {
            "@type": "java.util.ArrayList",
            "@items": [
              "uid"
            ]
          },
          "name": "nameAttr",
          "dataType": "string"
        }
      },
      "task": {
        "@type": "com.tremolosecurity.provisioning.customTasks.LoadGroups",
        "nameAttr": "uid",
        "inverse": false,
        "base": null
      },
      "onSuccess": null,
      "onFailure": null,
      "workflow": {
        "@ref": 1
      },
      "isOnHold": false,
      "isDone": false,
      "wasSuccess": false
    },
    {
      "@type": "com.tremolosecurity.provisioning.tasks.CustomTask",
      "className": "com.tremolosecurity.provisioning.customTasks.MapJitGroups",
      "params": {
        "groupMap": {
          "@type": "com.tremolosecurity.saml.Attribute",
          "values": {
            "@type": "java.util.ArrayList",
            "@items": [
              "k8s-cluster-administrators=CN=jit-k8s-admin,CN=Users,DC=ent2k12,DC=domain,DC=com",
              "administrators=CN=ouadmins,CN=Users,DC=ent2k12,DC=domain,DC=com"
            ]
          },
          "name": "groupMap",
          "dataType": "string"
        },
        "attributeName": {
          "@type": "com.tremolosecurity.saml.Attribute",
          "values": {
            "@type": "java.util.ArrayList",
            "@items": [
              "memberOf"
            ]
          },
          "name": "attributeName",
          "dataType": "string"
        }
      },
      "task": {
        "@type": "com.tremolosecurity.provisioning.customTasks.MapJitGroups",
        "groupMap": {
          "@type": "java.util.HashMap",
          "@keys": [
            {
              "@type": "com.novell.ldap.util.DN",
              "rdnList": [
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "CN"
                    ]
                  },
                  "values": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "jit-k8s-admin"
                    ]
                  },
                  "rawValue": "jit-k8s-admin"
                },
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "CN"
                    ]
                  },
                  "values": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "Users"
                    ]
                  },
                  "rawValue": "Users"
                },
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "DC"
                    ]
                  },
                  "values": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "ent2k12"
                    ]
                  },
                  "rawValue": "ent2k12"
                },
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "DC"
                    ]
                  },
                  "values": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "domain"
                    ]
                  },
                  "rawValue": "domain"
                },
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "DC"
                    ]
                  },
                  "values": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "com"
                    ]
                  },
                  "rawValue": "com"
                }
              ]
            },
            {
              "@type": "com.novell.ldap.util.DN",
              "rdnList": [
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "CN"
                    ]
                  },
                  "values": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "ouadmins"
                    ]
                  },
                  "rawValue": "ouadmins"
                },
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "CN"
                    ]
                  },
                  "values": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "Users"
                    ]
                  },
                  "rawValue": "Users"
                },
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "DC"
                    ]
                  },
                  "values": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "ent2k12"
                    ]
                  },
                  "rawValue": "ent2k12"
                },
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "DC"
                    ]
                  },
                  "values": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "domain"
                    ]
                  },
                  "rawValue": "domain"
                },
                {
                  "@type": "com.novell.ldap.util.RDN",
                  "types": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "DC"
                    ]
                  },
                  "values": {
                    "@type": "[Ljava.lang.String;",
                    "@items": [
                      "com"
                    ]
                  },
                  "rawValue": "com"
                }
              ]
            }
          ],
          "@items": [
            {
              "@type": "java.util.ArrayList",
              "@items": [
                "k8s-cluster-administrators"
              ]
            },
            {
              "@type": "java.util.ArrayList",
              "@items": [
                "administrators"
              ]
            }
          ]
        },
        "attributeName": "memberOf"
      },
      "onSuccess": null,
      "onFailure": null,
      "workflow": {
        "@ref": 1
      },
      "isOnHold": false,
      "isDone": false,
      "wasSuccess": false
    },
    {
      "@type": "com.tremolosecurity.provisioning.tasks.Mapping",
      "mapper": {
        "map": {
          "sub": {
            "@type": "com.tremolosecurity.provisioning.mapping.MappingEntry",
            "type": "userAttr",
            "destType": null,
            "userAttr": "uid",
            "staticValue": null,
            "mapping": null,
            "composite": null
          },
          "firstName": {
            "@type": "com.tremolosecurity.provisioning.mapping.MappingEntry",
            "type": "userAttr",
            "destType": null,
            "userAttr": "givenName",
            "staticValue": null,
            "mapping": null,
            "composite": null
          },
          "lastName": {
            "@type": "com.tremolosecurity.provisioning.mapping.MappingEntry",
            "type": "userAttr",
            "destType": null,
            "userAttr": "sn",
            "staticValue": null,
            "mapping": null,
            "composite": null
          },
          "TREMOLO_USER_ID": {
            "@type": "com.tremolosecurity.provisioning.mapping.MappingEntry",
            "type": "userAttr",
            "destType": null,
            "userAttr": "uid",
            "staticValue": null,
            "mapping": null,
            "composite": null
          },
          "mail": {
            "@type": "com.tremolosecurity.provisioning.mapping.MappingEntry",
            "type": "userAttr",
            "destType": null,
            "userAttr": "mail",
            "staticValue": null,
            "mapping": null,
            "composite": null
          }
        },
        "attributes": [
          "sub",
          "firstName",
          "lastName",
          "TREMOLO_USER_ID",
          "mail"
        ],
        "strict": false
      },
      "strict": true,
      "onSuccess": [
        {
          "@type": "com.tremolosecurity.provisioning.tasks.AddGroup",
          "name": "users",
          "remove": false,
          "onSuccess": null,
          "onFailure": null,
          "workflow": {
            "@ref": 1
          },
          "isOnHold": false,
          "isDone": false,
          "wasSuccess": false
        },
        {
          "@type": "com.tremolosecurity.provisioning.tasks.Provision",
          "isSync": true,
          "setPassword": false,
          "targetName": "jitdb",
          "onlyPassedInAttributes": false,
          "attributes": [
            "sub",
            "firstName",
            "lastName",
            "mail"
          ],
          "onSuccess": null,
          "onFailure": null,
          "workflow": {
            "@ref": 1
          },
          "isOnHold": false,
          "isDone": false,
          "wasSuccess": false
        },
        {
          "@type": "com.tremolosecurity.provisioning.tasks.Resync",
          "keepExternalAttrs": false,
          "changeRoot": true,
          "newRoot": "o=Tremolo",
          "onSuccess": null,
          "onFailure": null,
          "workflow": {
            "@ref": 1
          },
          "isOnHold": false,
          "isDone": false,
          "wasSuccess": false
        }
      ],
      "onFailure": [],
      "workflow": {
        "@ref": 1
      },
      "isOnHold": false,
      "isDone": false,
      "wasSuccess": false
    }
  ],
  "id": 0,
  "user": null,
  "requester": null,
  "request": null,
  "userNum": 0,
  "requesterNum": 0,
  "description": "JIT",
  "label": "JIT",
  "annotationFilters": {
    "@type": "java.util.HashMap"
  }
}
```

The difference I see is that in 4.15 the `rdnList`, for the type `com.novell.ldap.util.RDN` the `@type` is no set but in 4.16 its set to `[Ljava.lang.String;`.  It looks like there were some new options added.  did a default change that would cause this behavior?

Thanks

**Comment by jdereg** [comment]
Would you mind checking to see if this issue remains in version 4.18.0?

**Comment by mlbiam** [comment]
Confirmed. I first came across the issue when moving from 4.14-->4.18 but wanted to isolate which versions in particular the change happened

**Comment by jdereg** [comment]
Thank you for checking.  We'll check into this.

**Comment by jdereg** [comment]
In your "writeOptions" the default should be to show "minmal type info."
Is that set when you are writing the JSON output?.

Is it true that many of your source structure fields are of type String[]?

**Comment by jdereg** [comment]
A fix was added to address this issue.  Can you verify this works for you with json-io 4.19.1 version?

**Comment by mlbiam** [comment]
sorry for the delay in getting back to you.  just confirmed that 4.19.1 worked great!

**Comment by jdereg** [comment]
Marc,

Thank you for sharing the update.  Glad to hear the good news.
