### ISSUE TITLE
How to deserialise javafx classes with inaccessible fields?

### ISSUE THREAD

**Issue by williamclocksin** [jdereg/json-io#264]
Is there a special way to deserialise javafx classes with inaccessible fields?

Here is an example error message:

Caused by: com.cedarsoftware.util.io.JsonIoException: Cannot set field: red on class: javafx.scene.paint.Color as field is not acccessible.  Add a create a ClassFactory implementation to create the needed class, and use JsonReader.assignInstantiator() to associate your ClassFactory to the class: javafx.scene.paint.Color
	at com.cedarsoftware.util.io.MetaUtils.setFieldValue(MetaUtils.java:1111)
	at com.cedarsoftware.util.io.ObjectResolver.assignField(ObjectResolver.java:158)
... 55 more

**Comment by jdereg** [comment]
You need to write a ClassFactory (read/create) side, and a CustomWriter
(write) side.  These are used when the class you are working with has
private fields and cannot be accessed due to the newer protection of JDK
17+.

There is a new version of json-io coming out, within the next 1-2 weeks
that does simplify writing the ClassFactory (read side).  If you are going
to go this route, I would recommend getting familiar with the current
ClassFactory (for reading Json) and CustomWriter (for writing it).  The
changes will mostly affect the read-side - you will no longer use the
ClassFactory, but a simpler approach by adding a "converter" for your
custom type to the Converter class (which is updated in java-util).

**Comment by williamclocksin** [comment]
OK, understood.  I believe I use Javafx Color in only one field of one class, and I’ll need to write a custom reader/writer for that class anyway. I look forward to seeing what the Converter can do.
