### ISSUE TITLE
Problem deserializing ObservableObjects

### ISSUE THREAD

**Issue by octaviospain** [jdereg/json-io#42]
I'm coding a JavaFX application and I want to serialize/deserialize a list of objects that are observable cause they are used in a `TableView`. I tested that the serialization/deserialization with json-io of a `List` works well, but when I try to do the same thing with an `ObservableList` I get `JsonIoException` when calling `readObject()` from the `JsonReader` instance
This is the failure trace from JUnit

`com.cedarsoftware.util.io.JsonIoException: null
Last read: afx.beans.property.SimpleObjectProperty","bean":null,"name":"","value":{"@type":"java.time.LocalDate","year":2015,"month":6,"day":21},"observable":null,"listener":null,"valid":true,"helper":null}}]}}v
line: 1, col: 3721
	at com.cedarsoftware.util.io.JsonReader.convertParsedMapsToJava(JsonReader.java:598)
	at com.cedarsoftware.util.io.JsonReader.readObject(JsonReader.java:540)
	at tests.unit.LibraryJsonSerializeTest.testObservableListToLibrary(LibraryJsonSerializeTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.NullPointerException
	at com.sun.javafx.collections.ObservableListWrapper.size(ObservableListWrapper.java:94)
	at java.util.AbstractList.add(AbstractList.java:108)
	at com.cedarsoftware.util.io.ObjectResolver.traverseCollection(ObjectResolver.java:325)
	at com.cedarsoftware.util.io.Resolver.convertMapsToObjects(Resolver.java:122)
	at com.cedarsoftware.util.io.JsonReader.convertParsedMapsToJava(JsonReader.java:584)
	... 25 more`

Any ideas about the reason?

**Comment by jdereg** [comment]
If you notice near the end of the stack trace, the last 'Caused by:' entry, it says a NullPointerException occurred.  It occurred inside the ObservableListWrapper.size() method.  Taking a look at that method, you will see that all it does is call backingList.size().  The backingList member variable is obviously null, and calling size it causes the NPE.

This happens because during instantiation of the ObservableListWrapper, the backingList member variable is not getting set.  json-io allows you to assign your own 'instantiator' class for situations like this.  Use the JsonReader.assignInstantiator() method to assign your own JsonReader.ClassFactory class to be called when a new instance of ObservableListWrapper is needed:

    JsonReader.assignInstantiator(ObservableListWrapper.class, myObservableListWrapperCreator);

This will associate a JsonReader.ClassFactory instance to be call which will create the ObservableListWrapper when needed.

    public static class MyObservableListWrapperCreator implements JsonReader.ClassFactory
    {
        Object newInstance(Class c)
        {
            // properly create an new ObservableListWrapper and return it here
        }
    }

When the JsonReader encounters an ObservableListWrapper is needed to be created, it will call your factory class to get a new one.  Since you are in charge of writing that class, you can properly create a new ObservalListWrapper and return it.  

JsonReader does a lot of work to attempt to construct any class it encounters, including calling all constructors, private constructors, even using sun.misc.Unsafe if available.  However, some classes still require their constructors to be called.  This is why JsonReader has the ability to allow you to install your own 'constructors' as needed.

**Comment by octaviospain** [comment]
Ok that is nice, I see now the power of json-io with that feature. I readed twice your explanation and I search in the api but I can't figure how to "properly create an new ObservableListWrapper and return it here", given a Class as parameter. I checked the code of JsonReader's CollectionFactory class and I infered that the naive approach would be something like
```java
public class OberservableListWrapperCreator implements ClassFactory {

	@Override
	public Object newInstance(Class c) {
		if(ObservableListWrapper.class.isAssignableFrom(c))
				return new ObservableListWrapper(null);
		else
			throw new JsonIoException("CollectionFactory handed Class for which it was not expecting: " + c.getName());
	}
}
```
But obviously isn't. Sorry for my skills, can you tell me more about how I have to implement that? Thanks a lot

**Comment by jdereg** [comment]
First, you do not an 'isAssignableFrom' check.  Your code will only be
called with a ObservableListWrapper.class.  Passed whatever you need to
your ObservableListWrapperCreator in it's constructor that you would need
to make sure you create the class properly.  Currently, your class does not
have any constructor, so your 'newInstance(Class c)' method has no 'help'
to create the class.

I am not familiar with this particular class, but I am sure there is a
normal way to create an instance of ObservableListWrapper.  Create the
instance in this method, and then return it.  If you need some external
instances, those can be passed through your [missing] constructor, and then
used in the newInstance() method.

**Comment by octaviospain** [comment]
Thank you a lot, I just did it.
