### ISSUE TITLE
EnumSet not supported

### ISSUE THREAD

**Issue by francisu** [jdereg/json-io#55]
It has a problem because it can't be initialized with the normal constructor stuff.

Pull request to come in a little bit.

com.cedarsoftware.util.io.JsonIoException: class org.talend.components.api.properties.Property$Flags != null
Last read: title":"Restore Test"}]},"validationResult":null,"propertyValues":{"@type":"java.util.HashMap","@keys":[{"@ref":24},{"@ref":11}],"@items":["testPassword","testUser"]}},"returns":null,"REQUIRED":true}"
line: 1, col: 14352

	at com.cedarsoftware.util.io.JsonReader.convertParsedMapsToJava(JsonReader.java:600)
	at com.cedarsoftware.util.io.JsonReader.readObject(JsonReader.java:542)
	at com.cedarsoftware.util.io.JsonReader.jsonToJava(JsonReader.java:289)
	at com.cedarsoftware.util.io.JsonReader.jsonToJava(JsonReader.java:262)
	at org.talend.components.api.properties.ComponentProperties.fromSerialized(ComponentProperties.java:155)
	at org.talend.components.api.ComponentTestUtils.checkSerialize(ComponentTestUtils.java:34)
	at org.talend.components.api.properties.PropertiesTest.testSerializeValues(PropertiesTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassCastException: class org.talend.components.api.properties.Property$Flags != null
	at java.util.EnumSet.typeCheck(EnumSet.java:398)
	at java.util.RegularEnumSet.add(RegularEnumSet.java:161)
	at java.util.RegularEnumSet.add(RegularEnumSet.java:36)
	at com.cedarsoftware.util.io.ObjectResolver.traverseCollection(ObjectResolver.java:325)
	at com.cedarsoftware.util.io.Resolver.convertMapsToObjects(Resolver.java:122)
	at com.cedarsoftware.util.io.JsonReader.convertParsedMapsToJava(JsonReader.java:586)
	... 34 more

**Comment by jdereg** [comment]
This could have been resolved using json-io's feature that allows you to assign an 'instantiator' to a given Class.  In this case, you would have created (in your code) an instantiator and associated it to EnumSet.class.  However, since EnumSet is a JDK class, it does belong in json-io.  I am letting you know this for future reference, assignInstantiator() will allow you to get past any constructor that is difficult to instantiate past the tricks that json-io tries.
