### ISSUE TITLE
UnsupportedOperationException of Netty's SelectedSelectionKeySet.iterator()

### ISSUE THREAD

**Issue by visvadw** [jdereg/json-io#94]
Hello everybody,

This library looks promising. I just started playing with it (version `4.5.0`), but I got into an issue that I believe is related to `Netty` version `4.0.37.Final`:

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java -ea -Didea.launcher.port=7536 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA.app/Contents/bin" -Didea.junit.sm_runner -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit-rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/tools.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/files/dev/visva/focus/ng/target/test-classes:/files/dev/visva/focus/ng/target/classes:/Users/ilema/.m2/repository/joda-time/joda-time/2.9.4/joda-time-2.9.4.jar:/Users/ilema/.m2/repository/commons-configuration/commons-configuration/1.10/commons-configuration-1.10.jar:/Users/ilema/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/Users/ilema/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar:/Users/ilema/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar:/Users/ilema/.m2/repository/com/datastax/cassandra/cassandra-driver-core/3.1.0/cassandra-driver-core-3.1.0.jar:/Users/ilema/.m2/repository/io/netty/netty-handler/4.0.37.Final/netty-handler-4.0.37.Final.jar:/Users/ilema/.m2/repository/io/netty/netty-buffer/4.0.37.Final/netty-buffer-4.0.37.Final.jar:/Users/ilema/.m2/repository/io/netty/netty-common/4.0.37.Final/netty-common-4.0.37.Final.jar:/Users/ilema/.m2/repository/io/netty/netty-transport/4.0.37.Final/netty-transport-4.0.37.Final.jar:/Users/ilema/.m2/repository/io/netty/netty-codec/4.0.37.Final/netty-codec-4.0.37.Final.jar:/Users/ilema/.m2/repository/com/google/guava/guava/16.0.1/guava-16.0.1.jar:/Users/ilema/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2.jar:/Users/ilema/.m2/repository/com/github/jnr/jnr-ffi/2.0.7/jnr-ffi-2.0.7.jar:/Users/ilema/.m2/repository/com/github/jnr/jffi/1.2.10/jffi-1.2.10.jar:/Users/ilema/.m2/repository/com/github/jnr/jffi/1.2.10/jffi-1.2.10-native.jar:/Users/ilema/.m2/repository/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.jar:/Users/ilema/.m2/repository/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.jar:/Users/ilema/.m2/repository/org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.jar:/Users/ilema/.m2/repository/com/github/jnr/jnr-x86asm/1.0.2/jnr-x86asm-1.0.2.jar:/Users/ilema/.m2/repository/com/github/jnr/jnr-posix/3.0.27/jnr-posix-3.0.27.jar:/Users/ilema/.m2/repository/com/github/jnr/jnr-constants/0.9.0/jnr-constants-0.9.0.jar:/Users/ilema/.m2/repository/org/eclipse/jetty/jetty-webapp/9.3.11.v20160721/jetty-webapp-9.3.11.v20160721.jar:/Users/ilema/.m2/repository/org/eclipse/jetty/jetty-xml/9.3.11.v20160721/jetty-xml-9.3.11.v20160721.jar:/Users/ilema/.m2/repository/org/eclipse/jetty/jetty-util/9.3.11.v20160721/jetty-util-9.3.11.v20160721.jar:/Users/ilema/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.11.v20160721/jetty-servlet-9.3.11.v20160721.jar:/Users/ilema/.m2/repository/org/eclipse/jetty/jetty-security/9.3.11.v20160721/jetty-security-9.3.11.v20160721.jar:/Users/ilema/.m2/repository/org/eclipse/jetty/jetty-server/9.3.11.v20160721/jetty-server-9.3.11.v20160721.jar:/Users/ilema/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/Users/ilema/.m2/repository/org/eclipse/jetty/jetty-http/9.3.11.v20160721/jetty-http-9.3.11.v20160721.jar:/Users/ilema/.m2/repository/org/eclipse/jetty/jetty-io/9.3.11.v20160721/jetty-io-9.3.11.v20160721.jar:/Users/ilema/.m2/repository/org/eclipse/jetty/jetty-annotations/9.3.11.v20160721/jetty-annotations-9.3.11.v20160721.jar:/Users/ilema/.m2/repository/org/eclipse/jetty/jetty-plus/9.3.11.v20160721/jetty-plus-9.3.11.v20160721.jar:/Users/ilema/.m2/repository/org/eclipse/jetty/jetty-jndi/9.3.11.v20160721/jetty-jndi-9.3.11.v20160721.jar:/Users/ilema/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar:/Users/ilema/.m2/repository/org/ow2/asm/asm/5.0.1/asm-5.0.1.jar:/Users/ilema/.m2/repository/org/ow2/asm/asm-commons/5.0.1/asm-commons-5.0.1.jar:/Users/ilema/.m2/repository/org/jboss/resteasy/resteasy-jaxrs/3.0.19.Final/resteasy-jaxrs-3.0.19.Final.jar:/Users/ilema/.m2/repository/org/jboss/spec/javax/ws/rs/jboss-jaxrs-api_2.0_spec/1.0.0.Final/jboss-jaxrs-api_2.0_spec-1.0.0.Final.jar:/Users/ilema/.m2/repository/org/jboss/spec/javax/annotation/jboss-annotations-api_1.2_spec/1.0.0.Final/jboss-annotations-api_1.2_spec-1.0.0.Final.jar:/Users/ilema/.m2/repository/javax/activation/activation/1.1.1/activation-1.1.1.jar:/Users/ilema/.m2/repository/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.jar:/Users/ilema/.m2/repository/org/apache/httpcomponents/httpcore/4.3.3/httpcore-4.3.3.jar:/Users/ilema/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar:/Users/ilema/.m2/repository/commons-io/commons-io/2.1/commons-io-2.1.jar:/Users/ilema/.m2/repository/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar:/Users/ilema/.m2/repository/org/jboss/logging/jboss-logging/3.1.4.GA/jboss-logging-3.1.4.GA.jar:/Users/ilema/.m2/repository/org/jboss/resteasy/resteasy-client/3.0.19.Final/resteasy-client-3.0.19.Final.jar:/Users/ilema/.m2/repository/org/jboss/resteasy/async-http-servlet-3.0/3.0.19.Final/async-http-servlet-3.0-3.0.19.Final.jar:/Users/ilema/.m2/repository/org/jboss/resteasy/jaxrs-api/3.0.12.Final/jaxrs-api-3.0.12.Final.jar:/Users/ilema/.m2/repository/org/jboss/resteasy/resteasy-servlet-initializer/3.0.19.Final/resteasy-servlet-initializer-3.0.19.Final.jar:/Users/ilema/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar:/Users/ilema/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.21/log4j-over-slf4j-1.7.21.jar:/Users/ilema/.m2/repository/org/apache/logging/log4j/log4j-core/2.6.2/log4j-core-2.6.2.jar:/Users/ilema/.m2/repository/org/apache/logging/log4j/log4j-api/2.6.2/log4j-api-2.6.2.jar:/Users/ilema/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.6.2/log4j-slf4j-impl-2.6.2.jar:/Users/ilema/.m2/repository/com/cedarsoftware/json-io/4.5.0/json-io-4.5.0.jar:/Users/ilema/.m2/repository/junit/junit/4.12/junit-4.12.jar:/Users/ilema/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 repo.CassandraRepoTests
(begin)------- test 1: basic init -------
CassandraRepo> initially: '{
  "repoSettings":null,
  "cluster":null,
  "session":null,
  "inited":false,
  "error":null
}'.

com.cedarsoftware.util.io.JsonIoException: Unable to convert object to JSON

	at com.cedarsoftware.util.io.JsonWriter.objectToJson(JsonWriter.java:223)
	at ro.visva.focus.infra.persistence.cassandra.CassandraRepo.toJSON(CassandraRepo.java:137)
	at repo.CassandraRepoTests.test1_init(CassandraRepoTests.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.UnsupportedOperationException
	at io.netty.channel.nio.SelectedSelectionKeySet.iterator(SelectedSelectionKeySet.java:108)
	at com.cedarsoftware.util.io.JsonWriter.traceReferences(JsonWriter.java:720)
	at com.cedarsoftware.util.io.JsonWriter.write(JsonWriter.java:624)
	at com.cedarsoftware.util.io.JsonWriter.objectToJson(JsonWriter.java:217)
	... 29 more
```

I'll try to manually include the Netty's packages as dependencies, and using the currently latest version, `4.1.4.Final`. Meanwhile, if somebody encountered this problem also, please give a feedback.

Thank you.

**Comment by jdereg** [comment]
If you have trouble serializing an unusual class, like one that includes a
ClassLoader field for example, you can use the options map of the
JsonWriter to address the issue.  For example, if the class being
serialized has a field on it you do not want serialized, you can black list
the field.

**Comment by visvadw** [comment]
@jdereg Thanks for the feedback, John!

Yes, I am using a black list as you may see below. `CassandraRepo` is a singleton and there are two cases when `toJSON()` method is used:
- after the instantiation (using `CassandraRepo repo = CassandraRepo.getInstance();`) and it looks alright:
```
{
  "repoSettings":null,
  "cluster":null,
  "session":null,
  "initError":null,
  "error":null
}
```
- after the initialisation (using `repo.init(configRepo);`)
Here, it crashes:
```
com.cedarsoftware.util.io.JsonIoException: Unable to convert object to JSON

	at com.cedarsoftware.util.io.JsonWriter.objectToJson(JsonWriter.java:223)
	at ro.visva.focus.infra.persistence.cassandra.CassandraRepo.toJSON(CassandraRepo.java:141)
	at repo.CassandraRepoTests.test1_init(CassandraRepoTests.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	...
```

And here is the class used in this case:

```java
public class CassandraRepo implements Repo {

    private CassandraRepoSettings repoSettings;

    private static CassandraRepo instance;

    private Cluster cluster;

    private Session session;

    private Error initError;

    private Error error;

    private Logger log = LoggerFactory.getLogger(CassandraRepo.class);

    private CassandraRepo() {
        // private c'tor as being a singleton
    }

    public static CassandraRepo getInstance() {
        if (instance == null) instance = new CassandraRepo();
        return instance;
    }

   // ... content omitted ...

    /** Get the JSON format of this object. */
    public String toJSON() {

        List<String> blackList = new ArrayList<>();
        blackList.add("log");
        Map<Class, Object> blackListmap = new HashMap<>();
        blackListmap.put(this.getClass(), blackList);

        Map<String, Object> map = new HashMap<>();
        map.put(JsonWriter.TYPE, false);
        map.put(JsonWriter.PRETTY_PRINT, true);
        map.put(JsonWriter.FIELD_NAME_BLACK_LIST, blackListmap);
        return JsonWriter.objectToJson(this, map);
    }
}

```

There is indeed something wrong somewhere as indeed, the operation is not supported not even on the latest version of [netty-transport](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/SelectedSelectionKeySet.java):
```
    @Override
    public Iterator<SelectionKey> iterator() {
        throw new UnsupportedOperationException();
    }
```

Thank you.

**Comment by visvadw** [comment]
Black list was extended so that only two simple attributes (of class `Error`, a simple JavaBean style class) were left:
```
{
  "initError":null,
  "error":null
}
```
but the issue is still there. It appears even when all the attributes are in the black list, so that the first run shows:
```
{
  
}
```
when using:
```
        List<String> blackList = new ArrayList<>();
        blackList.add("log");
        blackList.add("repoSettings");
        blackList.add("cluster");
        blackList.add("session");
        blackList.add("initError");
        blackList.add("initError");
        blackList.add("error");
        Map<Class, Object> blackListmap = new HashMap<>();
        blackListmap.put(this.getClass(), blackList);

        Map<String, Object> map = new HashMap<>();
        map.put(JsonWriter.TYPE, false);
        map.put(JsonWriter.PRETTY_PRINT, true);
        map.put(JsonWriter.FIELD_NAME_BLACK_LIST, blackListmap);
        return JsonWriter.objectToJson(this, map);
```

**Comment by jdereg** [comment]
The issue you are hitting is that the implementation of a Map, (something like called SelectedSet), implements a .keySet() method, that returns a KeySet which does not support .iterator().  For now, can you either substitute in a different Map -or- not serialize this field?

**Comment by visvadw** [comment]
I understand your point of view, but none of the attributes of `CassandraRepo` example shown above uses `Map`. Anyway, for now I continued with GSON.
Thank you for the feedback!
